version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 10
    groups:
      # Group all npm development dependencies together
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      # Group all npm production dependencies together
      production-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    reviewers:
      - "anthonybaldwin"

  # Keep Docker dependencies up to date
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "anthonybaldwin"

  # Keep GitHub Actions up to date (for future workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "anthonybaldwin"